name: Build 
run-name: Build 

on:
  pull_request:
    branches:
      - "main"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v5

      - name: Install MinGW
        run: sudo apt install g++-mingw-w64-x86-64

      - name: Build
        run: sh build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: ${{ github.workspace }}/*.exe
          retention-days: 1
          if-no-files-found: warn